package com.github.antoniomauriciofg96.realestateapp.constants;

public enum TypeProperty {
	
	CASA,
	APARTAMENTO,
	QUARTO,
	CASA_DE_CONDOMINIO,
	COBERTURA,
	FLAT,
	KITNET,
	LOTE_TERRENO,
	SOBRADO,
	EDIFICIO_RESIDENCIAL,
	FAZENDA_SITIO_CHACARA,
	CONSULTORIO_COMERCIAL,
	GALPAO_DEPOSITO_ARMAZEM_COMERCIAL,
	IMOVEL_COMERCIAL,
	LOTE_TERRENO_COMERCIAL,
	PONTO_LOJA_BOX_COMERCIAL,
	SALA_CONJUNTO_COMERCIAL,
	PREDIO_COMERCIAL

}
